#include "ovpiCPluginObjectDescEnumAlgorithmGlobalDefinesGenerator.h"

using namespace OpenViBE;
using namespace OpenViBE::Kernel;
using namespace OpenViBE::Plugins;

#include <iostream>
#include <functional>

CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator::CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator(const IKernelContext& rKernelContext, const CString& sFilename)
	:CPluginObjectDescEnum(rKernelContext)
{
	m_oUsedIdentifiers.clear();

	OpenViBE::CString l_sFullFilename = sFilename + CString("/ovp_global_defines.h");

	getLogManager() << LogLevel_Info << "Writing global defines to '" << l_sFullFilename << "\n";

	m_oFile.open(l_sFullFilename.toASCIIString());

	OV_ERROR_UNLESS_K(
		m_oFile.good(),
		"Error opening '" << l_sFullFilename << "for writing.",
		OpenViBE::Kernel::ErrorType::BadFileRead,); // Please note the ",)" to simulate "return;"

	m_oFile << "#ifndef __OpenViBEPlugins_Global_Defines_H__\n";
	m_oFile << "#define __OpenViBEPlugins_Global_Defines_H__\n";
	m_oFile << "\n";
	m_oFile << "// This file was automatically generated by Plugin Inspector\n";
	m_oFile << "\n";
}

CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator::~CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator(void)
{
	if(!m_oFile.good()) return;

	m_oFile << "#endif // __OpenViBEPlugins_Global_Defines_H__\n";
	m_oFile.close();
}

void CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator::addIdentifier(const OpenViBE::CString &objectName, const OpenViBE::CIdentifier candidate, const OpenViBE::CString &sSpaces)
{
	if(m_oUsedIdentifiers.find(candidate) == m_oUsedIdentifiers.end() ) {
		m_oUsedIdentifiers[candidate]=objectName;
		m_oFile << "#define " << objectName << sSpaces << "OpenViBE::CIdentifier" << candidate.toString().toASCIIString() << "\n";
	} 
	else
	{
		OV_WARNING_K("    Object '" << objectName << "' has duplicate id " << candidate.toString().toASCIIString() << " with " << m_oUsedIdentifiers[candidate]);
		m_oFile << "#define " << objectName << sSpaces << "OpenViBE::CIdentifier" << candidate.toString().toASCIIString() << " // Duplicate of " << m_oUsedIdentifiers[candidate] << "\n";
	}
}

bool CPluginObjectDescEnumAlgorithmGlobalDefinesGenerator::callback(const IPluginObjectDesc& rPluginObjectDesc)
{
	OV_ERROR_UNLESS_KRF(
		m_oFile.good(),
		"Cannot use file; Was it opened correctly ?",
		OpenViBE::Kernel::ErrorType::BadProcessing);

	int l_iWidth=120;

	getLogManager() << LogLevel_Info << "  Dumping [" << rPluginObjectDesc.getName() << "]\n";

	IAlgorithmManager& l_rAlgorithmManager=m_rKernelContext.getAlgorithmManager();
	const CIdentifier l_oAlgorithmId = l_rAlgorithmManager.createAlgorithm(rPluginObjectDesc.getCreatedClass());
	OV_ERROR_UNLESS_KRF(
		l_oAlgorithmId != OV_UndefinedIdentifier,
		"  Unable to create algorithm",
		OpenViBE::Kernel::ErrorType::BadProcessing);

	IAlgorithmProxy& l_rAlgorithmProxy=l_rAlgorithmManager.getAlgorithm(l_oAlgorithmId);
	CIdentifier l_oIdentifier;

	m_oFile << "// -----------------------------------------------------\n";
	m_oFile << "// " << rPluginObjectDesc.getName().toASCIIString() << "\n";
	m_oFile << "// -----------------------------------------------------\n";
	m_oFile << "\n";

	l_rAlgorithmProxy.initialize();

	auto addIdentifierFromParameters = [&l_iWidth, &rPluginObjectDesc, this](const char* nameStart, const char* nameEnd, const CIdentifier& id, const CString& toAppend)
	{
		std::string l_sDefName;
		l_sDefName+=nameStart;
		l_sDefName+=transform(rPluginObjectDesc.getName().toASCIIString(), true);
		l_sDefName+=nameEnd;
		if (toAppend != CString(""))
		{
			l_sDefName+=transform(toAppend.toASCIIString(), true);
		}

		std::string l_sSpaces;
		l_sSpaces.resize(l_iWidth-l_sDefName.length(), ' ');

		addIdentifier(l_sDefName.c_str(), id, l_sSpaces.c_str());
	};

	addIdentifierFromParameters("OVP_GD_ClassId_Algorithm_", "", rPluginObjectDesc.getCreatedClassIdentifier(), "");
	addIdentifierFromParameters("OVP_GD_ClassId_Algorithm_", "Desc", rPluginObjectDesc.getCreatedClassIdentifier(), "");

	l_oIdentifier = OV_UndefinedIdentifier;
	while((l_oIdentifier=l_rAlgorithmProxy.getNextInputParameterIdentifier(l_oIdentifier))!=OV_UndefinedIdentifier)
	{
		addIdentifierFromParameters("OVP_GD_Algorithm_", "_InputParameterId_", l_oIdentifier, l_rAlgorithmProxy.getInputParameterName(l_oIdentifier));
	}

	l_oIdentifier = OV_UndefinedIdentifier;
	while((l_oIdentifier=l_rAlgorithmProxy.getNextOutputParameterIdentifier(l_oIdentifier))!=OV_UndefinedIdentifier)
	{
		addIdentifierFromParameters("OVP_GD_Algorithm_", "_OutputParameterId_", l_oIdentifier, l_rAlgorithmProxy.getOutputParameterName(l_oIdentifier));
	}

	l_oIdentifier = OV_UndefinedIdentifier;
	while((l_oIdentifier=l_rAlgorithmProxy.getNextInputTriggerIdentifier(l_oIdentifier))!=OV_UndefinedIdentifier)
	{
		addIdentifierFromParameters("OVP_GD_Algorithm_", "_InputTriggerId_", l_oIdentifier, l_rAlgorithmProxy.getInputTriggerName(l_oIdentifier));
	}

	l_oIdentifier = OV_UndefinedIdentifier;
	while((l_oIdentifier=l_rAlgorithmProxy.getNextOutputTriggerIdentifier(l_oIdentifier))!=OV_UndefinedIdentifier)
	{
		addIdentifierFromParameters("OVP_GD_Algorithm_", "_OutputTriggerId_", l_oIdentifier, l_rAlgorithmProxy.getOutputTriggerName(l_oIdentifier));
	}

	l_rAlgorithmProxy.uninitialize();

	m_oFile << "\n";

	l_rAlgorithmManager.releaseAlgorithm(l_rAlgorithmProxy);

	return true;
}
