# ---------------------------------
# Finds Python
# Adds library to target
# Adds include path
# ---------------------------------

GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_ThirdPartyPython)

IF(WIN32)
	FIND_PATH(PATH_PYTHON include/Python.h PATHS "c:/python27" ${OV_CUSTOM_DEPENDENCIES_PATH}	[HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\2.7\\InstallPath])
		
	IF(PATH_PYTHON)
		OV_PRINT(OV_PRINTED "  Found Python...")
		INCLUDE_DIRECTORIES(${PATH_PYTHON}/include)
		
		FILE(GLOB_RECURSE lib_files ${PATH_PYTHON}/libs/*.lib)
		
		FOREACH(PYTHON_LIB ${lib_files})
			OV_PRINT(OV_PRINTED "    [  OK  ] Third party lib ${PYTHON_LIB}")
			# TARGET_LINK_LIBRARIES(${PROJECT_NAME} debug ${PYTHON_LIB})
			TARGET_LINK_LIBRARIES(${PROJECT_NAME} optimized ${PYTHON_LIB})
		ENDFOREACH(PYTHON_LIB)
		
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} optimized Delayimp )
		SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/DELAYLOAD:python27.dll")

		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyPython)
	ELSE(PATH_PYTHON)
		OV_PRINT(OV_PRINTED "  FAILED to find Python")
	ENDIF(PATH_PYTHON)
ENDIF(WIN32)

IF(UNIX)
	# Prefert Python 2.7 supported by OV python-plugin
	SET(Python_ADDITIONAL_VERSIONS 2.7)
	INCLUDE("FindPythonLibs")
	IF(PYTHONLIBS_FOUND)
		OV_PRINT(OV_PRINTED "  Found Python...")
		INCLUDE_DIRECTORIES(${PYTHON_INCLUDE_PATH})
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PYTHON_LIBRARIES})
#		FOREACH(PYTHON_LIB ${PYTHON_LIBRARIES})
#			SET(PYTHON_LIB1 "PYTHON_LIB1-NOTFOUND")
#			FIND_LIBRARY(PYTHON_LIB1 NAMES ${PYTHON_LIB} PATHS NO_DEFAULT_PATH)
#			FIND_LIBRARY(PYTHON_LIB1 NAMES ${PYTHON_LIB} PATHS "/")
#			IF(PYTHON_LIB1)
#				OV_PRINT(OV_PRINTED "    [  OK  ] Third party lib ${PYTHON_LIB1}")
#				TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PYTHON_LIB1})
#			ELSE(PYTHON_LIB1)
#				OV_PRINT(OV_PRINTED "    [FAILED] Third party lib ${PYTHON_LIB}")
#			ENDIF(PYTHON_LIB1)
#		ENDFOREACH(PYTHON_LIB)

		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyPython)
	ELSE(PYTHONLIBS_FOUND)
		OV_PRINT(OV_PRINTED "  FAILED to find Python")	
	ENDIF(PYTHONLIBS_FOUND)
ENDIF(UNIX)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_ThirdPartyPython "Yes")

