# ---------------------------------
# Finds the ENOBIO API & library
# Adds library to target
# Adds include path
# ---------------------------------
IF(WIN32)
	SET(QTCORE_INCLUDE_PREFIX C:/Qt/4.8.6/include)
	SET(QTCORE_LIB_PREFIX C:/Qt/4.8.6/lib)
	SET(ENOBIOAPI_DIR ${OV_CUSTOM_DEPENDENCIES_PATH}/Enobio3GAPI.win32/enobio3G)

  	FIND_PATH(PATH_ENOBIOAPI enobio3g.h PATHS ${ENOBIOAPI_DIR})
	IF(NOT PATH_ENOBIOAPI)
		MESSAGE(STATUS "  FAILED to find ENOBIO API - cmake looked in '${ENOBIOAPI_DIR}', skipping Enobio.")
		RETURN()
	ENDIF(NOT PATH_ENOBIOAPI)
	
	MESSAGE(STATUS "  Found ENOBIO API...")

	FIND_LIBRARY(LIB_ENOBIOAPI Enobio3GAPI PATHS ${PATH_ENOBIOAPI}/../MSVC/ )
	IF(NOT LIB_ENOBIOAPI)
		MESSAGE(STATUS "    [FAILED] Enobio libs not found, skipping Enobio.")	
		RETURN()
	ENDIF(NOT LIB_ENOBIOAPI)
	
	FIND_PATH( PATH_QTINCLUDE QtCore/QMutex ${QTCORE_INCLUDE_PREFIX})
	IF(NOT PATH_QTINCLUDE)
		MESSAGE(STATUS "	[FAILED] to find QT Include, required for Enobio3G, skipping Enobio.")
		RETURN()
	ENDIF(NOT PATH_QTINCLUDE)		
	
	FIND_LIBRARY(LIB_QT QtCore4 ${QTCORE_LIB_PREFIX})
	IF(NOT LIB_QT)
		MESSAGE(STATUS "    [FAILED] Qt libs not found, required for Enobio3G, skipping Enobio.")	
		RETURN()
	ENDIF(NOT LIB_QT)
	
	INCLUDE_DIRECTORIES(${PATH_ENOBIOAPI})			
	INCLUDE_DIRECTORIES(${PATH_QTINCLUDE})
			
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_ENOBIOAPI} )
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_QT} )
	
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyEnobioAPI)	
	
	ADD_CUSTOM_COMMAND(
		TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND ${CMAKE_COMMAND}
		ARGS -E copy "${PATH_ENOBIOAPI}/../MSVC/Enobio3GAPI.dll" "${CMAKE_INSTALL_FULL_BINDIR}"
		COMMENT "      --->   Copying dll file ${PATH_ENOBIOAPI}/EnobioAPI.dll for the Enobio driver to bin/"
		VERBATIM)	
	ADD_CUSTOM_COMMAND(
		TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND ${CMAKE_COMMAND}
		ARGS -E copy "${PATH_ENOBIOAPI}/../MSVC/WinBluetoothAPI.dll" "${CMAKE_INSTALL_FULL_BINDIR}"
		COMMENT "      --->   Copying dll file ${PATH_ENOBIOAPI}/WinBluetoothAPI.dll for the Enobio driver to bin/"
		VERBATIM)						
	ADD_CUSTOM_COMMAND(
		TARGET ${PROJECT_NAME}
		POST_BUILD
		COMMAND ${CMAKE_COMMAND}
		ARGS -E copy "${PATH_QTINCLUDE}/../bin/QtCore4.dll" "${CMAKE_INSTALL_FULL_BINDIR}"
		COMMENT "      --->   Copying dll file ${PATH_QTINCLUDE}/../bin/QtCore4.dll for the Enobio driver to bin/"
		VERBATIM)	
		
	MESSAGE(STATUS "    [  OK  ] lib ${LIB_QT}")		
	MESSAGE(STATUS "    [  OK  ] lib ${LIB_ENOBIOAPI}")

ENDIF(WIN32)

IF(UNIX)
	SET(QTCORE_INCLUDE_PREFIX /usr/share/qt4/include/)
	SET(QTCORE_LIB_PREFIX /usr/lib/x86_64-linux-gnu/)
	
	FIND_PATH(PATH_ENOBIOAPI enobio3g.h PATHS $ENV{OpenViBE_dependencies} ${OV_BASE_DIR}/contrib/plugins/server-drivers/enobio3G/Enobio3GAPI.linux/)
	IF(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  Found ENOBIO API...")
		INCLUDE_DIRECTORIES(${PATH_ENOBIOAPI})
		FIND_PATH(PATH_QTCORE_INCLUDE QtCore/QtCore ${QTCORE_INCLUDE_PREFIX})
		IF(PATH_QTCORE_INCLUDE)
		  MESSAGE(STATUS "    [  OK  ] QtCore include ${PATH_QTCORE_INCLUDE}/")
		  INCLUDE_DIRECTORIES(${PATH_QTCORE_INCLUDE}/)
		ELSE(PATH_QTCORE_INCLUDE)
		  MESSAGE(STATUS "    FAILED TO FIND QtCore include PATH")
		ENDIF(PATH_QTCORE_INCLUDE)
		FIND_LIBRARY(LIB_ENOBIOAPI Enobio3GAPI PATHS ${PATH_ENOBIOAPI}/libs/ )
		IF(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [  OK  ] lib ${LIB_ENOBIOAPI}")
			TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_ENOBIOAPI} )
		ELSE(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [FAILED] lib ENOBIO")
		ENDIF(LIB_ENOBIOAPI)

		FIND_LIBRARY(LIB_QT QtCore ${QTCORE_LIB_PREFIX})
		IF(LIB_QT)
		  MESSAGE(STATUS "    [  OK  ] lib ${LIB_QT}")
		  TARGET_LINK_LIBRARIES(${PROJECT_NAME} -L${LIB_QT} -lQtCore)
		ELSE(LIB_QT)
		  MESSAGE(STATUS "    [  FAILED  ] lib QT ${QTCORE_LIB_PREFIX}")
		ENDIF(LIB_QT)
		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyEnobioAPI)
		
		# Copying the DLL file at postbuild
		ADD_CUSTOM_COMMAND(
				TARGET ${PROJECT_NAME}
				POST_BUILD
				COMMAND ${CMAKE_COMMAND}
				ARGS -E copy "${LIB_ENOBIOAPI}" "${PROJECT_SOURCE_DIR}/bin"
				COMMENT "      --->   Copying lib file ${LIB_ENOBIOAPI} for the Neuroelectrics Enobio driver."
			VERBATIM)
	ELSE(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  FAILED to find ENOBIO API - cmake looked in $ENV{OpenViBE_dependencies} and in ${OV_BASE_DIR}/contrib/plugins/server-drivers/enobio3G/Enobio3GAPI/")
	ENDIF(PATH_ENOBIOAPI)

ENDIF(UNIX)
