# ---------------------------------
# Finds LUA
# Adds library to target
# Adds include path
# ---------------------------------
IF(WIN32)
	FIND_PATH(LUA_INCLUDE_DIRS lua.h PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/lua/include NO_DEFAULT_PATH)
	IF(LUA_INCLUDE_DIRS)
	  SET(LUA_FOUND TRUE)
	ENDIF(LUA_INCLUDE_DIRS)
ELSEIF(UNIX)
	INCLUDE("FindThirdPartyPkgConfig")
	if(PLATFORM EQUAL "Fedora")
	  FIND_PACKAGE(Lua REQUIRED)
	else ()
	  pkg_check_modules(LUA lua5.1)
	endif()

ENDIF(WIN32)

IF(LUA_FOUND)
	MESSAGE(STATUS "  Found Lua... in '${LUA_INCLUDE_DIRS}'")

	IF(WIN32)
		FIND_LIBRARY(LUA_LIBRARIES lua5.1 PATHS ${LUA_INCLUDE_DIRS}/../lib NO_DEFAULT_PATH)
		FIND_LIBRARY(LUA_LIBRARIES lua5.1 PATHS ${LUA_INCLUDE_DIRS}/../lib)
	ENDIF(WIN32)

	IF(LUA_LIBRARIES)
		MESSAGE(STATUS "	[  OK  ] lib ${LUA_LIBRARIES}")

		INCLUDE_DIRECTORIES(${LUA_INCLUDE_DIRS})
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LUA_LIBRARIES})
		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyLua)
	ELSE(LUA_LIBRARIES)
		MESSAGE(STATUS "	[FAILED] lib lua5.1")
	ENDIF(LUA_LIBRARIES)

ELSE(LUA_FOUND)
	MESSAGE(STATUS "  FAILED to find Lua")
ENDIF(LUA_FOUND)

