
IF(WIN32)
	FIND_PATH(PATH_MICROMED dllMicromed.dll PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/sdk-micromed NO_DEFAULT_PATH)
ENDIF(WIN32)

IF(PATH_MICROMED)
	MESSAGE(STATUS "  Found Micromed dll...")

	INSTALL(PROGRAMS "${PATH_MICROMED}/dllMicromed.dll" DESTINATION "bin")
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyMicromed)
ELSE(PATH_MICROMED)
	MESSAGE(STATUS "  FAILED to find Micromed device dll (optional)")
ENDIF(PATH_MICROMED)
