# ---------------------------------
# Finds OpenViBE
# Adds library to target
# Adds include path
# ---------------------------------
GET_PROPERTY(OV_PRINTED GLOBAL PROPERTY OV_TRIED_OpenViBE)

OPTION(DYNAMIC_LINK_OPENVIBE "Dynamically link OpenViBE" ON)

IF(DYNAMIC_LINK_OPENVIBE)
	ADD_DEFINITIONS(-DOV_Shared)
ENDIF(DYNAMIC_LINK_OPENVIBE)

IF(DYNAMIC_LINK_OPENVIBE)
	SET(OPENVIBE_LINKING "")
ELSE(DYNAMIC_LINK_OPENVIBE)
	SET(OPENVIBE_LINKING "-static")
ENDIF(DYNAMIC_LINK_OPENVIBE)

set(SRC_DIR ${OV_BASE_DIR}/openvibe)

FIND_PATH(PATH_OPENVIBE include/openvibe/ov_all.h PATHS ${SRC_DIR} NO_DEFAULT_PATH)
IF(PATH_OPENVIBE)
	OV_PRINT(OV_PRINTED "  Found OpenViBE...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE}/include/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME} openvibe${OPENVIBE_LINKING})
	
	ADD_DEFINITIONS(-DTARGET_HAS_OpenViBE)
ELSE(PATH_OPENVIBE)
	OV_PRINT(OV_PRINTED "  FAILED to find OpenViBE...")
ENDIF(PATH_OPENVIBE)

SET_PROPERTY(GLOBAL PROPERTY OV_TRIED_OpenViBE "Yes")

