# ---------------------------------
# Finds STARLAB ENOBIO library
# Adds library to target
# Adds include path
# ---------------------------------
IF(WIN32)
SET(QTCORE_INCLUDE_PREFIX C:/Qt/4.8.6/include)
SET(QTCORE_LIB_PREFIX C:/Qt/4.8.6/lib)
SET(ENOBIOAPI_DIR ${OV_BASE_DIR}/contrib/plugins/server-drivers/enobio3G/Enobio3GAPI.win32/enobio3G)
  	FIND_PATH(PATH_ENOBIOAPI enobio3g.h PATHS $ENV{OpenViBE_dependencies} ${ENOBIOAPI_DIR})
	IF(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  Found ENOBIO API...")
		INCLUDE_DIRECTORIES(${PATH_ENOBIOAPI})
		FIND_LIBRARY(LIB_ENOBIOAPI Enobio3GAPI PATHS ${PATH_ENOBIOAPI}/../ )
		FIND_LIBRARY(LIB_QT QtCore4 ${QTCORE_LIB_PREFIX})
		IF(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [  OK  ] lib ${LIB_ENOBIOAPI}")
			TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_ENOBIOAPI} )
			TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_QT} )
		ELSE(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [FAILED] lib ENOBIO")
		ENDIF(LIB_ENOBIOAPI)

		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyEnobioAPI)

		FIND_PATH( PATH_QTINCLUDE QtCore/QMutex ${QTCORE_INCLUDE_PREFIX})
		IF(PATH_QTINCLUDE)
			MESSAGE(STATUS "  Found QT Include")
			INCLUDE_DIRECTORIES(${PATH_QTINCLUDE})
		ELSE(PATH_QTINCLUDE)
			MESSAGE(STATUS "	[FAILED] to find QT Include")
		ENDIF(PATH_QTINCLUDE)
		
		ADD_CUSTOM_COMMAND(
				TARGET ${PROJECT_NAME}
				POST_BUILD
				COMMAND ${CMAKE_COMMAND}
				ARGS -E copy "${PATH_ENOBIOAPI}/../Enobio3GAPI.dll" "${PROJECT_SOURCE_DIR}/bin"
				COMMENT "      --->   Copying dll file ${PATH_ENOBIOAPI}/EnobioAPI.dll for the STARLAB Enobio driver to ${PROJECT_SOURCE_DIR}/dependencies/lib."
			VERBATIM)
	ELSE(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  FAILED to find ENOBIO API - cmake looked in '${ENOBIOAPI_DIR}' and '$ENV{OpenViBE_dependencies}'")
	ENDIF(PATH_ENOBIOAPI)
ENDIF(WIN32)

IF(UNIX)
SET(QTCORE_INCLUDE_PREFIX /usr/share/qt4/include/)
SET(QTCORE_LIB_PREFIX /usr/lib/x86_64-linux-gnu/)
	FIND_PATH(PATH_ENOBIOAPI enobio3g.h PATHS $ENV{OpenViBE_dependencies} ${OV_BASE_DIR}/contrib/plugins/server-drivers/enobio3G/Enobio3GAPI.linux/)
	IF(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  Found ENOBIO API...")
		INCLUDE_DIRECTORIES(${PATH_ENOBIOAPI})
		FIND_PATH(PATH_QTCORE_INCLUDE QtCore/QtCore ${QTCORE_INCLUDE_PREFIX})
		IF(PATH_QTCORE_INCLUDE)
		  MESSAGE(STATUS "    [  OK  ] QtCore include ${PATH_QTCORE_INCLUDE}/")
		  INCLUDE_DIRECTORIES(${PATH_QTCORE_INCLUDE}/)
		ELSE(PATH_QTCORE_INCLUDE)
		  MESSAGE(STATUS "    FAILED TO FIND QtCore include PATH")
		ENDIF(PATH_QTCORE_INCLUDE)
		FIND_LIBRARY(LIB_ENOBIOAPI Enobio3GAPI PATHS ${PATH_ENOBIOAPI}/libs/ )
		IF(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [  OK  ] lib ${LIB_ENOBIOAPI}")
			TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_ENOBIOAPI} )
		ELSE(LIB_ENOBIOAPI)
			MESSAGE(STATUS "    [FAILED] lib ENOBIO")
		ENDIF(LIB_ENOBIOAPI)

		FIND_LIBRARY(LIB_QT QtCore ${QTCORE_LIB_PREFIX})
		IF(LIB_QT)
		  MESSAGE(STATUS "    [  OK  ] lib ${LIB_QT}")
		  TARGET_LINK_LIBRARIES(${PROJECT_NAME} -L${LIB_QT} -lQtCore)
		ELSE(LIB_QT)
		  MESSAGE(STATUS "    [  FAILED  ] lib QT ${QTCORE_LIB_PREFIX}")
		ENDIF(LIB_QT)
		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyEnobioAPI)
		
		# Copying the DLL file at postbuild
		ADD_CUSTOM_COMMAND(
				TARGET ${PROJECT_NAME}
				POST_BUILD
				COMMAND ${CMAKE_COMMAND}
				ARGS -E copy "${LIB_ENOBIOAPI}" "${PROJECT_SOURCE_DIR}/bin"
				COMMENT "      --->   Copying lib file ${LIB_ENOBIOAPI} for the Neuroelectrics Enobio driver."
			VERBATIM)
	ELSE(PATH_ENOBIOAPI)
		MESSAGE(STATUS "  FAILED to find ENOBIO API - cmake looked in $ENV{OpenViBE_dependencies} and in ${OV_BASE_DIR}/contrib/plugins/server-drivers/enobio3G/Enobio3GAPI/")
	ENDIF(PATH_ENOBIOAPI)

ENDIF(UNIX)
