# ---------------------------------
# Finds third party libs for NeuroServo driver
# Adds library to target
# Adds include path
# ---------------------------------

IF(WIN32)

	FIND_LIBRARY(LIB_STANDARD_MODULE_HID hid)
	IF(LIB_STANDARD_MODULE_HID)
		MESSAGE(STATUS "  Found HID library...")
	ELSE(LIB_STANDARD_MODULE_HID)
		MESSAGE(STATUS "  FAILED to find HID library (optional) ...")
	ENDIF(LIB_STANDARD_MODULE_HID)
	
	FIND_LIBRARY(LIB_STANDARD_MODULE_SETUPAPI SetupApi)
	IF(LIB_STANDARD_MODULE_SETUPAPI)
		MESSAGE(STATUS "  Found SetupApi library...")
	ELSE(LIB_STANDARD_MODULE_SETUPAPI)
		MESSAGE(STATUS "  FAILED to find SetupApi library (optional) ...")
	ENDIF(LIB_STANDARD_MODULE_SETUPAPI)

	IF(LIB_STANDARD_MODULE_HID AND LIB_STANDARD_MODULE_SETUPAPI)
		MESSAGE(STATUS "  Found all NeuroServo driver dependencies ...")
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_STANDARD_MODULE_HID})
		TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIB_STANDARD_MODULE_SETUPAPI})
		ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyNeuroServo)
	ELSE(LIB_STANDARD_MODULE_HID AND LIB_STANDARD_MODULE_SETUPAPI)
		MESSAGE(STATUS "  FAILED to find NeuroServo HID driver dependencies (optional) ...")
	ENDIF(LIB_STANDARD_MODULE_HID AND LIB_STANDARD_MODULE_SETUPAPI)

ENDIF(WIN32)

